services:
  # ----------------- Spark / JupyterLab -----------------
  spark:
    build: .
    container_name: tradecorp_training_spark
    env_file:
      - .env
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/home/jovyan/work

  #------------------ postgres -----------------------------
  postgres:
    image: postgres:13
    container_name: tradecorp_postgres
    environment:
      POSTGRES_USER: tradecorp
      POSTGRES_PASSWORD: tradecorp
      POSTGRES_DB: tradecorp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #---------------------- airflow ---------------------------
  airflow:
    build:
      context: .
      dockerfile: dockerfile.airflow
    container_name: tradecorp_airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://tradecorp:tradecorp@postgres/tradecorp
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - bash
      - -c
      - |
        set -e
        airflow db migrate
        airflow users create \
          --username "${AIRFLOW_ADMIN_USERNAME}" \
          --password "${AIRFLOW_ADMIN_PASSWORD}" \
          --firstname "Admin" \
          --lastname "TradeCorp" \
          --role "Admin" \
          --email "${AIRFLOW_ADMIN_EMAIL}" || true
        airflow webserver --port 8080 &
        exec airflow scheduler

volumes:
  postgres_data:
  airflow_postgres_data:
  airflow_logs:

